 adb shell pm uninstall -k --user 0 jp.co.sharp.android.LockWeatherWidget
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.SHWirelessOutput
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.antitok
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.backuprestore
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.backuprestore.provider
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.sharp.android.backuprestore.product
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.bluetoothpbappce
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.emopa.overlayservice
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.emopa.systemservice
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.emopar
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.emopar.internalcontent
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.emopar.internalcontent2
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.exchangepolicy
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.friendlink
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.inputmethodselector
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.iwnnime.ml
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.karadamate
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.kittingapp
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.kittingservice
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.kittingsuw
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.launcher3.simple
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.migratepicture
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.partnerlauncherprovider.simple
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.providers.soundmemo
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.providers.soundmemo.overlay.product
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.restoreguide
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.scshocapture2
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.service.hikarieffect
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.shaquoscastservice
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.sharpdatabackup
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.shframecapture
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.shmediaplayer
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.shrobodockservice
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.shselfcheck
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.dash.collector2
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.dash.uploader
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.siminsertionguide
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.soundmemo
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.soundmemo.overlay.product
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.startuptutorial_ps
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.sharp.android.startuptutorial_ps.common
 adb shell pm uninstall -k --user 0 jp.co.sharp.android.wallpaper3d
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.sharp.android.wallpaper3d.common
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.sharp.android.wallpaper3d.product
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.android.android.partnerbrowsercustomizations.forChrome.oem
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.android.keyguard.commonall
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.android.keyguard.product
 adb shell pm uninstall -k --user 0 jp.co.sharp.overlay.android.providers.partnerbookmarks.oem
 adb shell pm uninstall -k --user 0 sharp.jp.android.makersiteappli